packages:
  - 'packages/*'
  - 'packages/@cdktn/*'
  - 'examples/**'
  - 'tools/generate-function-bindings'
  - 'tools/documentation-generation'

allowBuilds:
  '@swc/core': true
  esbuild: true
  nx: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - jsii-rosetta@5.9.64

overrides:
  '@types/react': 18.3.28
