// Copyright (c) HashiCorp, Inc
// SPDX-License-Identifier: MPL-2.0

// This file is generated by tools/generate-function-bindings from
// function-availability/functions-matrix.json.
// To update it run 'pnpm update-function-matrix' followed by
// 'pnpm generate-function-availability' in tools/generate-function-bindings.

/**
 * Minimum CLI version per product required to use a Terraform function.
 * A missing product key means the function is not supported by that product
 * at any version.
 */
export interface FunctionVersionConstraints {
  readonly terraform?: string;
  readonly opentofu?: string;
}

/**
 * Terraform functions that are not universally available across all
 * supported Terraform (>=1.5.7) and OpenTofu
 * (>=1.6.0) releases. Functions absent from this map are
 * available everywhere and need no version validation.
 */
export const functionVersionConstraints: Record<
  string,
  FunctionVersionConstraints
> = {
  base64gunzip: { opentofu: ">=1.7.0" },
  cidrcontains: { opentofu: ">=1.7.0" },
  convert: { terraform: ">=1.15.0" },
  ephemeralasnull: { terraform: ">=1.10.0", opentofu: ">=1.11.0" },
  issensitive: { terraform: ">=1.8.0", opentofu: ">=1.7.0" },
  templatestring: { terraform: ">=1.9.0", opentofu: ">=1.7.0" },
  urldecode: { opentofu: ">=1.7.0" },
};
