// Copyright (c) HashiCorp, Inc
// SPDX-License-Identifier: MPL-2.0
import { AttributeModel } from "./models/attribute-model";
import { Struct } from "./models/struct";

/**
 * Terraform schemas describe nested blocks inline, so the generator names a
 * struct after the *path* that reaches it. A block shape reachable by many
 * paths is therefore emitted once per path -- together with its mapper
 * functions and its OutputReference/List classes, which are ~84% of the
 * generated bytes.
 *
 * That duplication is an artifact of the schema serialization, not of the
 * provider. `terraform providers schema -json` inlines every call site: in
 * DataDog's source a single `getComputeSchema()` is reached through
 * `getApmLogNetworkRumSecurityAuditQuerySchema()` (48 call sites) and four
 * sibling query helpers, and comes back out as 364 byte-identical interfaces.
 *
 * `detectAttributeLoops` already collapses a struct into an earlier one, but
 * only when the repeat appears among that struct's own ANCESTORS (true
 * recursion). Two identical shapes on sibling branches are never compared, and
 * every top-level attribute restarts detection from scratch. This pass closes
 * that gap: it compares every struct in the resource against every other and
 * repoints duplicates at a single canonical struct.
 *
 * NOTE ON EQUALITY: this deliberately does NOT reuse `getAttributeIdentifier`
 * from loop-detection. That comparison looks at attribute names plus ONE level
 * of nested structure -- safe for the ancestor-only case, but applied
 * resource-wide it merges structs that share a shallow shape and diverge
 * deeper (measured on datadog 4.18: it collapses
 * DashboardV2WidgetCohortDefinition into
 * DashboardV2WidgetGroupDefinitionWidgetSloListDefinition), which would emit
 * incorrect bindings. Equality here is a full recursive signature.
 */

// Reach the StructAttributeTypeModel through any collection wrappers. Only
// that class owns `struct` as an instance property; collections expose it as a
// prototype getter that delegates to their element type.
function structHolder(type: any): any | undefined {
  if (!type) return undefined;
  if (Object.prototype.hasOwnProperty.call(type, "struct") && type.struct) {
    return type;
  }
  if (type.elementType) return structHolder(type.elementType);
  return undefined;
}

function signature(struct: Struct, stack: Struct[]): string {
  // A struct already on the stack is a cycle (introduced by loop detection).
  // Encode how far up it points so equivalent cyclic shapes agree.
  const back = stack.indexOf(struct);
  if (back !== -1) return `@rec:${stack.length - back}`;

  const next = [...stack, struct];
  const parts = struct.attributes
    .map((a) => {
      const holder = structHolder(a.type);
      const inner = holder
        ? signature(holder.struct, next)
        : a.type.storedClassType;
      // typeModelType distinguishes list/set/map wrappers around one shape
      return [
        a.terraformName,
        a.optional ? "?" : "",
        a.computed ? "c" : "",
        a.type.typeModelType,
        inner,
      ].join(":");
    })
    .sort();

  // Flags that change what is emitted for an otherwise identical shape
  const flags = [
    struct.isClass ? "class" : "",
    struct.isAnonymous ? "anon" : "",
    struct.isSingleItem ? "single" : "",
    struct.nestingMode,
  ].join(",");

  return `{${parts.join("|")}}<${flags}>`;
}

function collect(attributes: AttributeModel[], found: Set<Struct>): void {
  for (const attr of attributes) {
    const holder = structHolder(attr.type);
    if (!holder) continue;
    const struct: Struct = holder.struct;
    if (found.has(struct)) continue; // also guards recursive structs
    found.add(struct);
    collect(struct.attributes, found);
  }
}

function repoint(
  attributes: AttributeModel[],
  canonical: Map<Struct, Struct>,
  seen: Set<Struct>,
): void {
  for (const attr of attributes) {
    const holder = structHolder(attr.type);
    if (!holder) continue;
    const target = canonical.get(holder.struct);
    if (target && target !== holder.struct) {
      // `struct` is readonly in TS only; every emitted name (storedClassType,
      // mapperName, outputReferenceName) derives from it, so repointing the
      // reference is enough to redirect the whole emission.
      holder.struct = target;
    }
    const struct: Struct = holder.struct;
    if (seen.has(struct)) continue;
    seen.add(struct);
    repoint(struct.attributes, canonical, seen);
  }
}

/**
 * Merges structurally identical structs within one resource.
 * @returns the structs that are no longer referenced and must be dropped from
 * the generator's struct registry.
 */
export function deduplicateStructs(attributes: AttributeModel[]): Set<Struct> {
  const all = new Set<Struct>();
  collect(attributes, all);

  const bySignature = new Map<string, Struct[]>();
  for (const struct of all) {
    const sig = signature(struct, []);
    const bucket = bySignature.get(sig);
    if (bucket) bucket.push(struct);
    else bySignature.set(sig, [struct]);
  }

  const canonical = new Map<Struct, Struct>();
  const removed = new Set<Struct>();
  for (const bucket of bySignature.values()) {
    if (bucket.length < 2) continue;
    // PLACEHOLDER NAMING -- see PR description. Shortest name, ties broken
    // lexicographically, so the winner does not depend on traversal order.
    // This is still not stable across provider releases (measured: 0.2-0.8% of
    // shapes renamed on datadog 4.17 -> 4.18) because the elected member can
    // leave the equivalence class. A signature -> name registry is the
    // intended fix and is NOT implemented here.
    const winner = [...bucket].sort(
      (a, b) => a.name.length - b.name.length || a.name.localeCompare(b.name),
    )[0];
    for (const struct of bucket) {
      canonical.set(struct, winner);
      if (struct !== winner) removed.add(struct);
    }
  }

  repoint(attributes, canonical, new Set());
  return removed;
}
