// Copyright (c) HashiCorp, Inc
// SPDX-License-Identifier: MPL-2.0
// --------------------------------------------------------------------------------
// This file defines context keys that enable certain features that are
// implemented behind a flag in order to preserve backwards compatibility for
// existing apps. When a new app is initialized through `cdk init`, the CLI will
// automatically add enable these features by adding them to the generated
// `cdktf.json` file. In the next major release of the CDK Terrain, these feature flags
// will be removed and will become the default behavior.
// --------------------------------------------------------------------------------

/**
 * This map includes context keys and values for feature flags that enable
 * capabilities "from the future", which we could not introduce as the default
 * behavior due to backwards compatibility for existing projects.
 *
 * New projects generated through `cdktn init` will include these flags in their
 * generated `cdktf.json` file.
 *
 * When we release the next major version of the CDK Terrain, we will flip the logic of
 * these features and clean up the `cdktf.json` generated by `cdktn init`.
 *
 * Tests must cover the default (disabled) case and the future (enabled) case.
 */
/**
 * When enabled, synthesis will throw an error if any constructs are scoped
 * directly to the App instead of to a TerraformStack.
 */
export const FAIL_ON_CONSTRUCTS_OUTSIDE_OF_STACKS =
  "failOnConstructsOutsideOfStacks";

/**
 * When enabled, each TerraformStack validates that the Terraform functions
 * used through `Fn` are supported by the runtime versions declared in
 * `targetVersions` (Terraform and/or OpenTofu). This is a purely static check
 * against the vendored function availability matrix; it never executes a
 * Terraform-compatible CLI.
 */
export const VALIDATE_FUNCTION_VERSIONS = "validateFunctionVersions";

/**
 * When enabled, TerraformAsset and TerraformModuleAsset compute asset hashes
 * with a canonical entry-framed scheme modeled on git trees and Nix NAR:
 * every entry contributes its type, permission mask (for files and
 * symlinks — the bits archiveSync preserves in zip external attributes),
 * relative path, payload size, and payload, in sorted order, and
 * directories — including empty ones — contribute explicit records. Renames,
 * entry-boundary shifts, mode changes, empty-directory changes, and
 * file-vs-symlink swaps all change the hash.
 *
 * When disabled, the legacy content-concatenation hash is kept for
 * compatibility: trees without symlinks hash byte-identically to earlier
 * releases, and only symlink-bearing trees (whose hashes had to change when
 * symlink following was fixed) get a tagged hash that separates symlink
 * metadata from file content.
 */
export const CANONICAL_ASSET_HASHES = "canonicalAssetHashes";

export const FUTURE_FLAGS = {
  [FAIL_ON_CONSTRUCTS_OUTSIDE_OF_STACKS]: "true",
  [VALIDATE_FUNCTION_VERSIONS]: "true",
  [CANONICAL_ASSET_HASHES]: "true",
};
