// Copyright (c) HashiCorp, Inc
// SPDX-License-Identifier: MPL-2.0

// Generates packages/cdktn/src/functions/function-availability.generated.ts
// from function-availability/functions-matrix.json.
//
// Only functions that are NOT universally available end up in the map:
// a function present since the first scanned release of both products
// (Terraform 1.5.7, OpenTofu 1.6.0) needs no validation and is omitted.
// A missing product key means the product does not support the function at
// any version. The matrix is expected to contain no removals — if one is
// recorded this script fails so the simple `>=` constraint model gets
// revisited deliberately.

import * as fs from "fs";
import * as path from "path";
import prettier from "prettier";
import { FUNCTIONS_MATRIX_FILE, FunctionsMatrix, ProductName } from "./matrix";

const OUTPUT_FILE = path.resolve(
  __dirname,
  "..",
  "..",
  "..",
  "packages",
  "cdktn",
  "src",
  "functions",
  "function-availability.generated.ts",
);

async function main() {
  const matrix: FunctionsMatrix = JSON.parse(
    fs.readFileSync(FUNCTIONS_MATRIX_FILE).toString(),
  );

  const products: ProductName[] = ["terraform", "opentofu"];
  const baseline = Object.fromEntries(
    products.map((p) => [p, matrix.versions[p][0]]),
  ) as Record<ProductName, string>;

  const entries: string[] = [];
  for (const name of Object.keys(matrix.functions).sort()) {
    const entry = matrix.functions[name];

    for (const product of products) {
      const availability = entry.products[product];
      if (availability?.removed || availability?.gaps?.length) {
        throw new Error(
          `Function ${name} was removed or has availability gaps in ${product} — ` +
            `the >=constraint model in this generator no longer holds, please revisit.`,
        );
      }
    }

    const universal = products.every(
      (p) => entry.products[p]?.introduced === baseline[p],
    );
    if (universal) continue;

    const constraints = products
      .filter((p) => entry.products[p])
      .map((p) => `${p}: ">=${entry.products[p]!.introduced}"`);
    entries.push(`  ${JSON.stringify(name)}: { ${constraints.join(", ")} },`);
  }

  const code = `// Copyright (c) HashiCorp, Inc
// SPDX-License-Identifier: MPL-2.0

// This file is generated by tools/generate-function-bindings from
// function-availability/functions-matrix.json.
// To update it run 'pnpm update-function-matrix' followed by
// 'pnpm generate-function-availability' in tools/generate-function-bindings.

/**
 * Minimum CLI version per product required to use a Terraform function.
 * A missing product key means the function is not supported by that product
 * at any version.
 */
export interface FunctionVersionConstraints {
  readonly terraform?: string;
  readonly opentofu?: string;
}

/**
 * Terraform functions that are not universally available across all
 * supported Terraform (>=${baseline.terraform}) and OpenTofu
 * (>=${baseline.opentofu}) releases. Functions absent from this map are
 * available everywhere and need no version validation.
 */
export const functionVersionConstraints: Record<
  string,
  FunctionVersionConstraints
> = {
${entries.join("\n")}
};
`;

  fs.writeFileSync(
    OUTPUT_FILE,
    await prettier.format(code, { parser: "babel-ts" }),
  );
  console.log(`wrote ${OUTPUT_FILE} (${entries.length} constrained functions)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
