---
name: Export CI/CD Traces to Scout
"on":
  workflow_run:
    workflows: ["*"]
    types:
      - completed
jobs:
  otel-export:
    runs-on: ubuntu-latest
    steps:
      - name: Export workflow trace
        uses: base-14/otel-cicd-action@v2
        with:
          otlpEndpoint: ${{ secrets.SCOUT_OTLP_ENDPOINT }}
          otelServiceName: cdk-terrain-ci
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
          tokenUrl: >-
            https://id.b14.dev/realms/${{
            secrets.SCOUT_TENANT
            }}/protocol/openid-connect/token
          appName: ${{ secrets.SCOUT_CLIENT_ID }}
          apiKey: ${{ secrets.SCOUT_CLIENT_SECRET }}
          audience: b14collector
