name: Depcheck
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches:
      - main
jobs:
  depcheck:
    runs-on: ubuntu-latest
    container:
      image: terraconstructs/jsii-terraform@sha256:c46ac91c8be20947a2b0e27a517eb4a5bfc015c16a27341876ed0b04d734ddf5
    env:
      CHECKPOINT_DISABLE: "1"
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        package: [
            cdktn,
            # cdktn-cli,
            "@cdktn/hcl2json",
            "@cdktn/hcl2cdk",
            "@cdktn/hcl-tools",
            "@cdktn/provider-schema",
            "@cdktn/provider-generator",
            "@cdktn/commons",
            # "@cdktn/cli-core",
          ]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Run Depcheck"
        run: |
          npx lerna exec --scope '${{ matrix.package }}' -- npx -y depcheck --ignores="@types/*,jsii,jsii-pacmak,jsii-docgen,yoga-layout-prebuilt,eslint,jest,tsc-files,typescript,esbuild,esbuild-jest,graphology-types"
